default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128

Subway:
    use_recurrent: true
    max_steps: 5.0e5
    sequence_length: 64
    num_layers: 2
    hidden_units: 256
    memory_size: 256
    beta: 1.0e-2
    gamma: 0.99
    num_epoch: 3
    buffer_size: 2000
    batch_size: 320
    max_steps: 5.0e5
    summary_freq: 2000
    time_horizon: 128
    normalize: false
    learning_rate: 1e-3
    

    